name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the project
        # run: python -m build
        run: |
          cd python/cicd_release
          python -m build

      - name: Create GitHub Release
        id: create_release
        # uses: actions/create-release@v1
        uses: actions/create-release@v1.1.4
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automatic release for version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # cd python/cicd_release
          asset_path: ./dist/*.tar.gz
          # asset_path: python/cicd_release/dist/*.tar.gz
          asset_name: myproject-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip